apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      securityContext:
            runAsUser: 0
            privileged: true
      containers:
        - name: agent
          image: jenkins/inbound-agent:4.13.3-1
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: JENKINS_URL
              value: http://localhost:8080
            - name: JENKINS_AGENT_NAME
              value: fixed-agent
            - name: JENKINS_SECRET
              value: 
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: docker-bin
              mountPath: /usr/bin/docker
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker